// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package vproxy.poc.grpc;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
