FROM wkgcass/vproxy-runtime:latest

ADD vproxy.jar /vproxy.jar
ADD libvfdposix.so /libvfdposix.so
ADD libvpxdp.so /libvpxdp.so
ADD libbpf.so /libbpf.so

RUN mkdir -p /var/run/docker
RUN mkdir -p /x-var

ENTRYPOINT []
CMD []
