/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_CxPlatProcessEventLocals */
#ifndef _Included_io_vproxy_msquic_CxPlatProcessEventLocals
#define _Included_io_vproxy_msquic_CxPlatProcessEventLocals
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_CxPlatExecutionState.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_msquic_CxPlatProcessEventLocals___getLayoutByteSize();

PNIEnvExpand(CxPlatProcessEventLocals, struct CxPlatProcessEventLocals *)
PNIBufExpand(CxPlatProcessEventLocals, struct CxPlatProcessEventLocals, JavaCritical_io_vproxy_msquic_CxPlatProcessEventLocals___getLayoutByteSize())

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_CxPlatProcessEventLocals
// metadata.generator-version: pni 22.0.0.17
// sha256:b0c1efea2fabd595552d65affeaf90fd54593640c46799c011edc69cb7467428
