/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_CxPlatExecutionState */
#ifndef _Included_io_vproxy_msquic_CxPlatExecutionState
#define _Included_io_vproxy_msquic_CxPlatExecutionState
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_msquic_CxPlatExecutionState___getLayoutByteSize();

PNIEnvExpand(CXPLAT_EXECUTION_STATE, CXPLAT_EXECUTION_STATE *)
PNIBufExpand(CXPLAT_EXECUTION_STATE, CXPLAT_EXECUTION_STATE, JavaCritical_io_vproxy_msquic_CxPlatExecutionState___getLayoutByteSize())

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_CxPlatExecutionState
// metadata.generator-version: pni 22.0.0.17
// sha256:e24a21e9f9672c96c7f8642e7dc7ccd5fd9d1d1f3a5390dc7a5917f89875ca77
