/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_posix_UDPRecvResultIPv6ST */
#ifndef _Included_io_vproxy_vfd_posix_UDPRecvResultIPv6ST
#define _Included_io_vproxy_vfd_posix_UDPRecvResultIPv6ST
#ifdef __cplusplus
extern "C" {
#endif

struct UDPRecvResultIPv6_st;
typedef struct UDPRecvResultIPv6_st UDPRecvResultIPv6_st;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_vfd_posix_SocketAddressIPv6ST.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(UDPRecvResultIPv6_st, UDPRecvResultIPv6_st *)
PNIBufExpand(UDPRecvResultIPv6_st, UDPRecvResultIPv6_st, 48)

struct UDPRecvResultIPv6_st {
    SocketAddressIPv6_st addr;
    uint32_t len;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_posix_UDPRecvResultIPv6ST
// metadata.generator-version: pni 22.0.0.17
// sha256:eca93935d7223a7dae878f4a500c5fc13ac1a45f26e341aa52fbea0e435e7a2c
