/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_fubuki_FubukiUpcall */
#ifndef _Included_io_vproxy_fubuki_FubukiUpcall
#define _Included_io_vproxy_fubuki_FubukiUpcall
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL JavaCritical_io_vproxy_fubuki_FubukiUpcall_onPacket(void * packet, int64_t len, void * ctx);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_fubuki_FubukiUpcall_addAddress(int32_t addr, int32_t netmask, void * ctx);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_fubuki_FubukiUpcall_deleteAddress(int32_t addr, int32_t netmask, void * ctx);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_fubuki_FubukiUpcall
// metadata.generator-version: pni 22.0.0.17
// sha256:ca1571e327cfea68ee8d9c0a4f747cc9e7f61337d9ebe74d59d6ceec6a72e2ee
