/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_fubuki_FubukiStartOptions */
#ifndef _Included_io_vproxy_fubuki_FubukiStartOptions
#define _Included_io_vproxy_fubuki_FubukiStartOptions
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "fubuki.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(FubukiStartOptions, struct FubukiStartOptions *)
PNIBufExpand(FubukiStartOptions, struct FubukiStartOptions, 64)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_fubuki_FubukiStartOptions
// metadata.generator-version: pni 22.0.0.17
// sha256:fa830160a996d5439eab54174b6579cc16b0aaf846f73a7dd68f9552028a453f
