/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_fubuki_FubukiHandle */
#ifndef _Included_io_vproxy_fubuki_FubukiHandle
#define _Included_io_vproxy_fubuki_FubukiHandle
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "fubuki.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(FubukiHandle, struct FubukiHandle *)
PNIBufExpand(FubukiHandle, struct FubukiHandle, (0 /* !!invalid!! */))

JNIEXPORT int32_t JNICALL fubuki_block_on(struct FubukiHandle * self, char * errorMsg);
JNIEXPORT void JNICALL if_to_fubuki(struct FubukiHandle * self, void * data, uint64_t len);
JNIEXPORT void JNICALL fubuki_stop(struct FubukiHandle * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_fubuki_FubukiHandle
// metadata.generator-version: pni 22.0.0.17
// sha256:104f90bb7750bbfb7493f3fe6ac4c72614f34112bc04ff7ebabd6dc388a204c5
