/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_windows_SockaddrStorage */
#ifndef _Included_io_vproxy_vfd_windows_SockaddrStorage
#define _Included_io_vproxy_vfd_windows_SockaddrStorage
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "ws2def.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(sockaddr_storage, struct sockaddr_storage *)
PNIBufExpand(sockaddr_storage, struct sockaddr_storage, 128)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_windows_SockaddrStorage
// metadata.generator-version: pni 22.0.0.17
// sha256:c0b7b88ca5a18c620a0f6adc68a725888ecc5cf001b0f727b8ab74c2d6b7559e
