/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_posix_SocketAddressIPv6ST */
#ifndef _Included_io_vproxy_vfd_posix_SocketAddressIPv6ST
#define _Included_io_vproxy_vfd_posix_SocketAddressIPv6ST
#ifdef __cplusplus
extern "C" {
#endif

struct SocketAddressIPv6_st;
typedef struct SocketAddressIPv6_st SocketAddressIPv6_st;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(SocketAddressIPv6_st, SocketAddressIPv6_st *)
PNIBufExpand(SocketAddressIPv6_st, SocketAddressIPv6_st, 42)

struct SocketAddressIPv6_st {
    char ip[40];
    uint16_t port;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_posix_SocketAddressIPv6ST
// metadata.generator-version: pni 22.0.0.17
// sha256:aaa1f5409b6212999b7ad6313c96eef7152bc87458c1e2a2c49d9420ea0da9de
