/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_windows_OverlappedEntry */
#ifndef _Included_io_vproxy_vfd_windows_OverlappedEntry
#define _Included_io_vproxy_vfd_windows_OverlappedEntry
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "minwinbase.h"
#include "io_vproxy_vfd_windows_Overlapped.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(OVERLAPPED_ENTRY, OVERLAPPED_ENTRY *)
PNIBufExpand(OVERLAPPED_ENTRY, OVERLAPPED_ENTRY, 32)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_windows_OverlappedEntry
// metadata.generator-version: pni 22.0.0.17
// sha256:01a1384a36ffc7f6adf3f2de34f83bce9784d41f46e38c55d398f57d836c4697
