/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_posix_AEFiredExtra */
#ifndef _Included_io_vproxy_vfd_posix_AEFiredExtra
#define _Included_io_vproxy_vfd_posix_AEFiredExtra
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "ae.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(aeFiredExtra, aeFiredExtra *)
PNIBufExpand(aeFiredExtra, aeFiredExtra, 16)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_posix_AEFiredExtra
// metadata.generator-version: pni 22.0.0.17
// sha256:595ce71b28bd3e30b28e60c987f50e4b3a34fa4e4dc97be03e87bcd9c086814b
