/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_MsQuicMod2 */
#ifndef _Included_io_vproxy_msquic_MsQuicMod2
#define _Included_io_vproxy_msquic_MsQuicMod2
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_QuicExtraApiTable.h"
#include "io_vproxy_msquic_CxPlatProcessEventLocals.h"
#include "io_vproxy_vfd_posix_AEFiredExtra.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_MsQuicMod2_WorkerThreadInit(QUIC_EXTRA_API_TABLE * api, struct CxPlatProcessEventLocals * CxPlatWorkerThreadLocals);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_MsQuicMod2_WorkerThreadBeforePoll(QUIC_EXTRA_API_TABLE * api, struct CxPlatProcessEventLocals * CxPlatProcessEventLocals);
JNIEXPORT uint8_t JNICALL JavaCritical_io_vproxy_msquic_MsQuicMod2_WorkerThreadAfterPoll(QUIC_EXTRA_API_TABLE * api, struct CxPlatProcessEventLocals * locals, int32_t num, aeFiredExtra * events);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_MsQuicMod2_WorkerThreadFinalize(QUIC_EXTRA_API_TABLE * api, struct CxPlatProcessEventLocals * CxPlatWorkerThreadLocals);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_MsQuicMod2
// metadata.generator-version: pni 22.0.0.17
// sha256:2b219ea4cf2ac3f697f0812ba12772ce8f80a7665378abfc2db67d632ff65844
