/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_posix_AEFiredEvent */
#ifndef _Included_io_vproxy_vfd_posix_AEFiredEvent
#define _Included_io_vproxy_vfd_posix_AEFiredEvent
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "ae.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(aeFiredEvent, aeFiredEvent *)
PNIBufExpand(aeFiredEvent, aeFiredEvent, 8)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_posix_AEFiredEvent
// metadata.generator-version: pni 22.0.0.17
// sha256:41e379ecdef8320f542114f302912f6319f85415e5c962ca4ef10db79b71de1d
