/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vfd_windows_GeneralWindows */

#ifndef _Included_vfd_windows_GeneralWindows
#define _Included_vfd_windows_GeneralWindows
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vfd_windows_GeneralWindows
 * Method:    tapNonBlockingSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_vfd_windows_GeneralWindows_tapNonBlockingSupported
  (JNIEnv *, jobject);

/*
 * Class:     vfd_windows_GeneralWindows
 * Method:    createTapFD
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vfd_windows_GeneralWindows_createTapFD
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vfd_windows_GeneralWindows
 * Method:    closeHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vfd_windows_GeneralWindows_closeHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vfd_windows_GeneralWindows
 * Method:    read
 * Signature: (JLjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_vfd_windows_GeneralWindows_read
  (JNIEnv *, jobject, jlong, jobject, jint, jint);

/*
 * Class:     vfd_windows_GeneralWindows
 * Method:    write
 * Signature: (JLjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_vfd_windows_GeneralWindows_write
  (JNIEnv *, jobject, jlong, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
