/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_posix_AEFiredEvent */
#ifndef _Included_io_vproxy_vfd_posix_AEFiredEvent
#define _Included_io_vproxy_vfd_posix_AEFiredEvent
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "ae.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(aeFiredEvent, aeFiredEvent *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_posix_AEFiredEvent
// metadata.generator-version: pni 21.0.0.8
// sha256:099c51b69ab39758fc64382489cca12d0bef3e83700607c46ad0e1228e2b47e8
