/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_posix_SocketAddressUDSST */
#ifndef _Included_io_vproxy_vfd_posix_SocketAddressUDSST
#define _Included_io_vproxy_vfd_posix_SocketAddressUDSST
#ifdef __cplusplus
extern "C" {
#endif

struct SocketAddressUDS_st;
typedef struct SocketAddressUDS_st SocketAddressUDS_st;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(SocketAddressUDS_st, SocketAddressUDS_st *)

PNI_PACK(struct, SocketAddressUDS_st, {
    char path[4096];
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_posix_SocketAddressUDSST
// metadata.generator-version: pni 21.0.0.8
// sha256:987679a1fe50aa0766942e1bd50c86ceeee1494675c2b439c9418cf03934b204
