/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_CxPlatProcessEventLocals */
#ifndef _Included_io_vproxy_msquic_CxPlatProcessEventLocals
#define _Included_io_vproxy_msquic_CxPlatProcessEventLocals
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_CxPlatExecutionState.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(CxPlatProcessEventLocals, struct CxPlatProcessEventLocals *)

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_msquic_CxPlatProcessEventLocals___getLayoutByteSize();

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_CxPlatProcessEventLocals
// metadata.generator-version: pni 21.0.0.11
// sha256:6e323284b6a3cac19f48b2105f58d3cf7c36acddb2fc76996073338cc262c60c
