/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_MsQuicModUpcall */
#ifndef _Included_io_vproxy_msquic_MsQuicModUpcall
#define _Included_io_vproxy_msquic_MsQuicModUpcall
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_MsQuicModUpcall_dispatch(void * worker, int32_t epfd, void * thread, void * context);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_MsQuicModUpcall
// metadata.generator-version: pni 21.0.0.8
// sha256:47a7533483653b8bb0ea4b7346925aff27e14bf6b571804f2755e313c13cd46d
