/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_posix_SocketAddressUnion */
#ifndef _Included_io_vproxy_vfd_posix_SocketAddressUnion
#define _Included_io_vproxy_vfd_posix_SocketAddressUnion
#ifdef __cplusplus
extern "C" {
#endif

union SocketAddressUnion;
typedef union SocketAddressUnion SocketAddressUnion;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_vfd_posix_SocketAddressIPv4ST.h"
#include "io_vproxy_vfd_posix_SocketAddressIPv6ST.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(SocketAddressUnion, SocketAddressUnion *)
PNIBufExpand(SocketAddressUnion, SocketAddressUnion, 42)

union SocketAddressUnion {
    SocketAddressIPv4_st v4;
    SocketAddressIPv6_st v6;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_posix_SocketAddressUnion
// metadata.generator-version: pni 22.0.0.17
// sha256:64053b5106b961599d2072adef45802472adfc519b116532760ed3714408b4b8
