/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_fubuki_FubukiStartOptions */
#ifndef _Included_io_vproxy_fubuki_FubukiStartOptions
#define _Included_io_vproxy_fubuki_FubukiStartOptions
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "fubuki.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(FubukiStartOptions, struct FubukiStartOptions *)
PNIBufExpand(FubukiStartOptions, struct FubukiStartOptions, 48)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_fubuki_FubukiStartOptions
// metadata.generator-version: pni 21.0.0.17
// sha256:c5c7e479ad02db3e3adb4c83a89e23f3826c23ab7e34d96fcc009427b2d26546
