/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_windows_HANDLE */
#ifndef _Included_io_vproxy_vfd_windows_HANDLE
#define _Included_io_vproxy_vfd_windows_HANDLE
#ifdef __cplusplus
extern "C" {
#endif

struct dummyHANDLE;
typedef struct dummyHANDLE dummyHANDLE;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(dummyHANDLE, dummyHANDLE *)
PNIBufExpand(dummyHANDLE, dummyHANDLE, (0 /* !!invalid!! */))

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_windows_HANDLE
// metadata.generator-version: pni 22.0.0.17
// sha256:f024833918c089b23a7f4e0bcaaed7d38fca08bb8e416cc37405ffc9a2dd8c28
