/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_modified_CxPlatProcessEventLocals */
#ifndef _Included_io_vproxy_msquic_modified_CxPlatProcessEventLocals
#define _Included_io_vproxy_msquic_modified_CxPlatProcessEventLocals
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(CxPlatProcessEventLocals, struct CxPlatProcessEventLocals *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_modified_CxPlatProcessEventLocals
// metadata.generator-version: pni 21.0.0.8
// sha256:56e6c9437739643e621781c4f3d135cefc1259b8a394e807f6bb943a586a37ba
