/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_CxPlatProcessEventLocals */
#ifndef _Included_io_vproxy_msquic_CxPlatProcessEventLocals
#define _Included_io_vproxy_msquic_CxPlatProcessEventLocals
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(CxPlatProcessEventLocals, struct CxPlatProcessEventLocals *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_CxPlatProcessEventLocals
// metadata.generator-version: pni 21.0.0.8
// sha256:03c6ff4c14ede7c9df9455eee7467706601d0411d86ed433fb068c8cce425db2
