/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicRegistrationConfigEx */
#ifndef _Included_io_vproxy_msquic_QuicRegistrationConfigEx
#define _Included_io_vproxy_msquic_QuicRegistrationConfigEx
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_msquic_QuicRegistrationConfig.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicRegistrationConfigEx, QuicRegistrationConfigEx *)
PNIBufExpand(QuicRegistrationConfigEx, QuicRegistrationConfigEx, 24)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicRegistrationConfigEx
// metadata.generator-version: pni 21.0.0.12
// sha256:d035282b9d6bc93df016641f35a9e2d68d0f8d9b9de8058c1f6c97cf1b45392f
