/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_windows_Overlapped */
#ifndef _Included_io_vproxy_vfd_windows_Overlapped
#define _Included_io_vproxy_vfd_windows_Overlapped
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "minwinbase.h"
#include "io_vproxy_vfd_windows_HANDLE.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(OVERLAPPED, OVERLAPPED *)
PNIBufExpand(OVERLAPPED, OVERLAPPED, 32)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_windows_Overlapped
// metadata.generator-version: pni 22.0.0.17
// sha256:64bedb16fd587e5ef172be5e417bf42a5ea1ca3335de6a325a3f967b75eee06b
