/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_posix_SocketAddressIPv4ST */
#ifndef _Included_io_vproxy_vfd_posix_SocketAddressIPv4ST
#define _Included_io_vproxy_vfd_posix_SocketAddressIPv4ST
#ifdef __cplusplus
extern "C" {
#endif

struct SocketAddressIPv4_st;
typedef struct SocketAddressIPv4_st SocketAddressIPv4_st;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(SocketAddressIPv4_st, SocketAddressIPv4_st *)
PNIBufExpand(SocketAddressIPv4_st, SocketAddressIPv4_st, 8)

struct SocketAddressIPv4_st {
    uint32_t ip;
    uint16_t port;
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_posix_SocketAddressIPv4ST
// metadata.generator-version: pni 21.0.0.13
// sha256:1deb685569468c49e814695f28c184c41a41007d8781d79a93026a6cc603b434
