/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_windows_PNISockaddrStorage */
#ifndef _Included_io_vproxy_vfd_windows_PNISockaddrStorage
#define _Included_io_vproxy_vfd_windows_PNISockaddrStorage
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "ws2def.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(sockaddr_storage, struct sockaddr_storage *)
PNIBufExpand(sockaddr_storage, struct sockaddr_storage, 128)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_windows_PNISockaddrStorage
// metadata.generator-version: pni 22.0.0.17
// sha256:2fa4a32ab294a23407552d9ff83c56849ebb3b8779fbcabe93b1461fe534f743
