/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_posix_SocketAddressIPv6ST */
#ifndef _Included_io_vproxy_vfd_posix_SocketAddressIPv6ST
#define _Included_io_vproxy_vfd_posix_SocketAddressIPv6ST
#ifdef __cplusplus
extern "C" {
#endif

struct SocketAddressIPv6_st;
typedef struct SocketAddressIPv6_st SocketAddressIPv6_st;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(SocketAddressIPv6_st, SocketAddressIPv6_st *)

PNI_PACK(struct, SocketAddressIPv6_st, {
    char ip[40];
    uint16_t port;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_posix_SocketAddressIPv6ST
// metadata.generator-version: pni 21.0.0.8
// sha256:d0f2fdc5ee8291bd8f9e6a08e17b470073f33255e6e4cb46d3b525fcd035487e
