/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_posix_UDPRecvResultIPv4ST */
#ifndef _Included_io_vproxy_vfd_posix_UDPRecvResultIPv4ST
#define _Included_io_vproxy_vfd_posix_UDPRecvResultIPv4ST
#ifdef __cplusplus
extern "C" {
#endif

struct UDPRecvResultIPv4_st;
typedef struct UDPRecvResultIPv4_st UDPRecvResultIPv4_st;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_vfd_posix_SocketAddressIPv4ST.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(UDPRecvResultIPv4_st, UDPRecvResultIPv4_st *)

PNI_PACK(struct, UDPRecvResultIPv4_st, {
    SocketAddressIPv4_st addr;
    uint32_t len;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_posix_UDPRecvResultIPv4ST
// metadata.generator-version: pni 21.0.0.8
// sha256:b9bdbd7f189d604bb58c6a0825c0f21b62c95ea25b8ef964ad4cec89c28cc265
