/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_fubuki_FubukiHandle */
#ifndef _Included_io_vproxy_fubuki_FubukiHandle
#define _Included_io_vproxy_fubuki_FubukiHandle
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "fubuki.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(FubukiHandle, struct FubukiHandle *)
PNIBufExpand(FubukiHandle, struct FubukiHandle, (0 /* !!invalid!! */))

JNIEXPORT void JNICALL if_to_fubuki(struct FubukiHandle * self, void * data, uint64_t len);
JNIEXPORT void JNICALL fubuki_stop(struct FubukiHandle * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_fubuki_FubukiHandle
// metadata.generator-version: pni 21.0.0.17
// sha256:cf2624b656ae5ff3e2d538d7f1e2503ef01839bf8db3f4cca7df1db96a610e56
