/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_posix_AEFiredExtra */
#ifndef _Included_io_vproxy_vfd_posix_AEFiredExtra
#define _Included_io_vproxy_vfd_posix_AEFiredExtra
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "ae.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(aeFiredExtra, aeFiredExtra *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_posix_AEFiredExtra
// metadata.generator-version: pni 21.0.0.8
// sha256:ba08fb78ee0976a942e5aa7251776fb26dfbb99b8c429b4e1ae722418cd6e2de
