/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_fubuki_FubukiFunc */
#ifndef _Included_io_vproxy_fubuki_FubukiFunc
#define _Included_io_vproxy_fubuki_FubukiFunc
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "fubuki.h"
#include "io_vproxy_fubuki_FubukiHandle.h"
#include "io_vproxy_fubuki_FubukiStartOptions.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT struct FubukiHandle * JNICALL fubuki_start(struct FubukiStartOptions * opts, uint32_t version, char * errorMsg);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_fubuki_FubukiFunc
// metadata.generator-version: pni 21.0.0.17
// sha256:ecc5fd51d9baa86631cc719fc59f54e87cc9c142e8df1728e7178fabf9fadcc9
