/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_CxPlatExecutionState */
#ifndef _Included_io_vproxy_msquic_CxPlatExecutionState
#define _Included_io_vproxy_msquic_CxPlatExecutionState
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(CXPLAT_EXECUTION_STATE, CXPLAT_EXECUTION_STATE *)

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_msquic_CxPlatExecutionState___getLayoutByteSize();

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_CxPlatExecutionState
// metadata.generator-version: pni 21.0.0.11
// sha256:2a8f3afd2f23be2714ab9a6f0de37181324ac4ed21fbe060b6ceb0f90bd421cf
