/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_modified_MsQuic */
#ifndef _Included_io_vproxy_msquic_modified_MsQuic
#define _Included_io_vproxy_msquic_modified_MsQuic
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"
#include "io_vproxy_msquic_modified_CxPlatProcessEventLocals.h"
#include "io_vproxy_vfd_posix_AEFiredExtra.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_msquic_modified_MsQuic_getCxPlatProcessEventLocalsMemorySize(void);
JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_msquic_modified_MsQuic_getCXPLAT_EXECUTION_STATEMemorySize(void);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_modified_MsQuic_MsQuicCxPlatWorkerThreadInit(struct CxPlatProcessEventLocals * CxPlatWorkerThreadLocals);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_msquic_modified_MsQuic_MsQuicCxPlatWorkerThreadBeforePoll(struct CxPlatProcessEventLocals * CxPlatProcessEventLocals);
JNIEXPORT uint8_t JNICALL JavaCritical_io_vproxy_msquic_modified_MsQuic_MsQuicCxPlatWorkerThreadAfterPoll(struct CxPlatProcessEventLocals * locals, int32_t num, aeFiredExtra * events);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_modified_MsQuic_MsQuicCxPlatWorkerThreadFinalize(struct CxPlatProcessEventLocals * CxPlatWorkerThreadLocals);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_modified_MsQuic_MsQuicSetEventLoopThreadDispatcher(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_modified_MsQuic_CxPlatGetCurThread(void * Thread);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_modified_MsQuic
// metadata.generator-version: pni 21.0.0.8
// sha256:32b81e745b48b91621c937bb4eb1b5e3e8f676e42e169eae7e410bce24c2edde
