/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_windows_WSABUF */
#ifndef _Included_io_vproxy_vfd_windows_WSABUF
#define _Included_io_vproxy_vfd_windows_WSABUF
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "ws2def.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(WSABUF, WSABUF *)
PNIBufExpand(WSABUF, WSABUF, 16)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_windows_WSABUF
// metadata.generator-version: pni 22.0.0.17
// sha256:8c71160d18bd841de2d81afae72b5d79695389794a94804dc8724a19bde273ea
