/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_posix_SocketAddressUDSST */
#ifndef _Included_io_vproxy_vfd_posix_SocketAddressUDSST
#define _Included_io_vproxy_vfd_posix_SocketAddressUDSST
#ifdef __cplusplus
extern "C" {
#endif

struct SocketAddressUDS_st;
typedef struct SocketAddressUDS_st SocketAddressUDS_st;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(SocketAddressUDS_st, SocketAddressUDS_st *)
PNIBufExpand(SocketAddressUDS_st, SocketAddressUDS_st, 4096)

struct SocketAddressUDS_st {
    char path[4096];
};

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_posix_SocketAddressUDSST
// metadata.generator-version: pni 21.0.0.13
// sha256:bd767cf26c06968dc5a755a3b904fa79a9b32519c3ea1c514dc8be583258c019
