/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_modified_MsQuicUpcall */
#ifndef _Included_io_vproxy_msquic_modified_MsQuicUpcall
#define _Included_io_vproxy_msquic_modified_MsQuicUpcall
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "msquic.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_msquic_modified_MsQuicUpcall_dispatch(void * worker, int32_t eventQ, void * thread);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_modified_MsQuicUpcall
// metadata.generator-version: pni 21.0.0.8
// sha256:e2843d25721aa2b63a266e31a5faaaa78eb4d5dddd059f5995dbcded4a13452f
