/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_posix_SocketAddressIPv4ST */
#ifndef _Included_io_vproxy_vfd_posix_SocketAddressIPv4ST
#define _Included_io_vproxy_vfd_posix_SocketAddressIPv4ST
#ifdef __cplusplus
extern "C" {
#endif

struct SocketAddressIPv4_st;
typedef struct SocketAddressIPv4_st SocketAddressIPv4_st;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(SocketAddressIPv4_st, SocketAddressIPv4_st *)

PNI_PACK(struct, SocketAddressIPv4_st, {
    uint32_t ip;
    uint16_t port; /* padding */ uint64_t :16;
});

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_posix_SocketAddressIPv4ST
// metadata.generator-version: pni 21.0.0.8
// sha256:1dcbf16b3e4179763cfe91f15fb7323fc8754394025075b4aff22759cbe9b9b4
