/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_msquic_QuicRegistrationConfigEx */
#ifndef _Included_io_vproxy_msquic_QuicRegistrationConfigEx
#define _Included_io_vproxy_msquic_QuicRegistrationConfigEx
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_msquic_QuicRegistrationConfig.h"

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(QuicRegistrationConfigEx, QuicRegistrationConfigEx *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_msquic_QuicRegistrationConfigEx
// metadata.generator-version: pni 21.0.0.11
// sha256:d3a79f36f7f7eb9dba3e9ab4074371261602b3544f14fab9aff7bfeff66ada0e
