/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_vfd_windows_SOCKET */
#ifndef _Included_io_vproxy_vfd_windows_SOCKET
#define _Included_io_vproxy_vfd_windows_SOCKET
#ifdef __cplusplus
extern "C" {
#endif

struct dummySOCKET;
typedef struct dummySOCKET dummySOCKET;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(dummySOCKET, dummySOCKET *)
PNIBufExpand(dummySOCKET, dummySOCKET, (0 /* !!invalid!! */))

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_vfd_windows_SOCKET
// metadata.generator-version: pni 22.0.0.17
// sha256:fc4860fc6b2215f71edaf3dab54fee604ebdeb60075cadff0c64daa42f8a68c7
