/* DO NOT EDIT THIS FILE - it is machine generated */

#include <stdint.h>

#include <jni.h>
#include "env.h"
/* Header for class io_vproxy_vfd_windows_GeneralWindows */

#ifndef _Included_io_vproxy_vfd_windows_GeneralWindows
#define _Included_io_vproxy_vfd_windows_GeneralWindows
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_vproxy_vfd_windows_GeneralWindows
 * Method:    tapNonBlockingSupported
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_io_vproxy_vfd_windows_GeneralWindows_tapNonBlockingSupported
  (JEnv *);

/*
 * Class:     io_vproxy_vfd_windows_GeneralWindows
 * Method:    allocateOverlapped
 * Signature: ()J
 */
JNIEXPORT void JNICALL Java_io_vproxy_vfd_windows_GeneralWindows_allocateOverlapped
  (JEnv *);

/*
 * Class:     io_vproxy_vfd_windows_GeneralWindows
 * Method:    releaseOverlapped
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_vproxy_vfd_windows_GeneralWindows_releaseOverlapped
  (JEnv *, jlong);

/*
 * Class:     io_vproxy_vfd_windows_GeneralWindows
 * Method:    createTapHandle
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT void JNICALL Java_io_vproxy_vfd_windows_GeneralWindows_createTapHandle
  (JEnv *, char *);

/*
 * Class:     io_vproxy_vfd_windows_GeneralWindows
 * Method:    closeHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_vproxy_vfd_windows_GeneralWindows_closeHandle
  (JEnv *, jlong);

/*
 * Class:     io_vproxy_vfd_windows_GeneralWindows
 * Method:    read
 * Signature: (JLjava/nio/ByteBuffer;IIJ)I
 */
JNIEXPORT void JNICALL Java_io_vproxy_vfd_windows_GeneralWindows_read
  (JEnv *, jlong, void *, jint, jint, jlong);

/*
 * Class:     io_vproxy_vfd_windows_GeneralWindows
 * Method:    write
 * Signature: (JLjava/nio/ByteBuffer;IIJ)I
 */
JNIEXPORT void JNICALL Java_io_vproxy_vfd_windows_GeneralWindows_write
  (JEnv *, jlong, void *, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
