/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "env.h"
/* Header for class io_vproxy_xdp_NativeXDP */

#ifndef _Included_io_vproxy_xdp_NativeXDP
#define _Included_io_vproxy_xdp_NativeXDP
#ifdef __cplusplus
extern "C" {
#endif
#undef io_vproxy_xdp_NativeXDP_VP_CSUM_NO
#define io_vproxy_xdp_NativeXDP_VP_CSUM_NO 0L
#undef io_vproxy_xdp_NativeXDP_VP_CSUM_IP
#define io_vproxy_xdp_NativeXDP_VP_CSUM_IP 1L
#undef io_vproxy_xdp_NativeXDP_VP_CSUM_UP
#define io_vproxy_xdp_NativeXDP_VP_CSUM_UP 2L
#undef io_vproxy_xdp_NativeXDP_VP_CSUM_ALL
#define io_vproxy_xdp_NativeXDP_VP_CSUM_ALL 3L
/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    loadAndAttachBPFProgramToNic0
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IZ)J
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_loadAndAttachBPFProgramToNic
  (JEnv *, char *, char *, char *, uint32_t, uint8_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    detachBPFProgramFromNic0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_detachBPFProgramFromNic
  (JEnv *, char *);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    findMapByNameInBPF0
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_findMapByNameInBPF
  (JEnv *, uint64_t, char *);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    createUMem0
 * Signature: (IIIII)J
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_createUMem
  (JEnv *, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    shareUMem0
 * Signature: (J)J
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_shareUMem
  (JEnv *, uint64_t);

typedef struct {
    char*    buffer;
    uint32_t len;
} __attribute__((packed)) buf_st;

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    getBufferFromUMem0
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_getBufferFromUMem
  (JEnv *, uint64_t, buf_st *);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    getBufferAddressFromUMem0
 * Signature: (J)J
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_getBufferAddressFromUMem
  (JEnv *, uint64_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    createXSK0
 * Signature: (Ljava/lang/String;IJIIIZIZ)J
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_createXSK
  (JEnv *, char *, uint32_t, uint64_t, uint32_t, uint32_t, uint32_t, uint8_t, uint32_t, uint8_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    addXSKIntoMap0
 * Signature: (JIJ)V
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_addXSKIntoMap
  (JEnv *, uint64_t, uint32_t, uint64_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    addMacIntoMap0
 * Signature: (J[BJ)V
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_addMacIntoMap
  (JEnv *, uint64_t, char *, uint64_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    removeMacFromMap0
 * Signature: (J[B)V
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_removeMacFromMap
  (JEnv *, uint64_t, char *);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    getFDFromXSK0
 * Signature: (J)I
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_getFDFromXSK
  (JEnv *, uint64_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    fillUpFillRing0
 * Signature: (J)V
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_fillUpFillRing
  (JEnv *, uint64_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    fetchPackets0
 * Signature: (J[J[J[I[I[I[I[I)I
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_fetchPackets0
  (JEnv *, uint64_t, uint32_t, uint64_t *, uint64_t *, uint32_t *, uint32_t *, uint32_t *, uint32_t *, uint32_t *);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    rxRelease0
 * Signature: (JI)V
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_rxRelease
  (JEnv *, uint64_t, uint32_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    writePacket0
 * Signature: (JJ)Z
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_writePacket
  (JEnv *, uint64_t, uint64_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    writePackets0
 * Signature: (JI[J)I
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_writePackets
  (JEnv *, uint64_t, uint32_t, uint64_t *);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    completeTx0
 * Signature: (J)V
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_completeTx
  (JEnv *, uint64_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    fetchChunk0
 * Signature: (J[J[J[I[I[I[I[I)Z
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_fetchChunk0
  (JEnv *, uint64_t, uint64_t *, uint64_t *, uint32_t *, uint32_t *, uint32_t *, uint32_t *, uint32_t *);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    setChunk0
 * Signature: (JIII)V
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_setChunk
  (JEnv *, uint64_t, uint32_t, uint32_t, uint32_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    releaseChunk0
 * Signature: (JJ)V
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_releaseChunk
  (JEnv *, uint64_t, uint64_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    addChunkRefCnt0
 * Signature: (J)V
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_addChunkRefCnt
  (JEnv *, uint64_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    releaseXSK0
 * Signature: (J)V
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_releaseXSK
  (JEnv *, uint64_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    releaseUMem0
 * Signature: (JZ)V
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_releaseUMem
  (JEnv *, uint64_t, uint8_t);

/*
 * Class:     io_vproxy_xdp_NativeXDP
 * Method:    releaseBPFObject0
 * Signature: (J)V
 */
JNIEXPORT int JNICALL Java_io_vproxy_xdp_NativeXDP_releaseBPFObject
  (JEnv *, uint64_t);

#ifdef __cplusplus
}
#endif
#endif
