/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vproxy_xdp_NativeXDP */

#ifndef _Included_vproxy_xdp_NativeXDP
#define _Included_vproxy_xdp_NativeXDP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    loadAndAttachBPFProgramToNic
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IZ)J
 */
JNIEXPORT jlong JNICALL Java_vproxy_xdp_NativeXDP_loadAndAttachBPFProgramToNic
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jboolean);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    findMapByNameInBPF
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_vproxy_xdp_NativeXDP_findMapByNameInBPF
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    createUMem
 * Signature: (IIIII)J
 */
JNIEXPORT jlong JNICALL Java_vproxy_xdp_NativeXDP_createUMem
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    getBufferFromUMem
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_vproxy_xdp_NativeXDP_getBufferFromUMem
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    createXSK
 * Signature: (Ljava/lang/String;IJIIIZ)J
 */
JNIEXPORT jlong JNICALL Java_vproxy_xdp_NativeXDP_createXSK
  (JNIEnv *, jobject, jstring, jint, jlong, jint, jint, jint, jboolean);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    addXSKIntoMap
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_vproxy_xdp_NativeXDP_addXSKIntoMap
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    getFDFromXSK
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_vproxy_xdp_NativeXDP_getFDFromXSK
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    fillUpFillRing
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vproxy_xdp_NativeXDP_fillUpFillRing
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    fetchPackets
 * Signature: (JLvproxy/xdp/ChunkPrototypeObjectList;)V
 */
JNIEXPORT void JNICALL Java_vproxy_xdp_NativeXDP_fetchPackets
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    rxRelease
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_vproxy_xdp_NativeXDP_rxRelease
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    writePacket
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_vproxy_xdp_NativeXDP_writePacket
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    completeTx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vproxy_xdp_NativeXDP_completeTx
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    fetchChunk
 * Signature: (JLvproxy/xdp/Chunk;)Z
 */
JNIEXPORT jboolean JNICALL Java_vproxy_xdp_NativeXDP_fetchChunk
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    setChunk
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_vproxy_xdp_NativeXDP_setChunk
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    releaseChunk
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_vproxy_xdp_NativeXDP_releaseChunk
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    addChunkRefCnt
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vproxy_xdp_NativeXDP_addChunkRefCnt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    releaseXSK
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vproxy_xdp_NativeXDP_releaseXSK
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    releaseUMem
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_vproxy_xdp_NativeXDP_releaseUMem
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     vproxy_xdp_NativeXDP
 * Method:    releaseBPFObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vproxy_xdp_NativeXDP_releaseBPFObject
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
