/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vproxy_vfd_posix_GeneralPosix */

#ifndef _Included_vproxy_vfd_posix_GeneralPosix
#define _Included_vproxy_vfd_posix_GeneralPosix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    pipeFDSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_vproxy_vfd_posix_GeneralPosix_pipeFDSupported
  (JNIEnv *, jobject);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    onlySelectNow
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_vproxy_vfd_posix_GeneralPosix_onlySelectNow
  (JNIEnv *, jobject);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    aeReadable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vproxy_vfd_posix_GeneralPosix_aeReadable
  (JNIEnv *, jobject);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    aeWritable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vproxy_vfd_posix_GeneralPosix_aeWritable
  (JNIEnv *, jobject);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    openPipe
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_vproxy_vfd_posix_GeneralPosix_openPipe
  (JNIEnv *, jobject);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    aeCreateEventLoop
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_vproxy_vfd_posix_GeneralPosix_aeCreateEventLoop
  (JNIEnv *, jobject, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    aeApiPoll0
 * Signature: (JJ[I[I)I
 */
JNIEXPORT jint JNICALL Java_vproxy_vfd_posix_GeneralPosix_aeApiPoll0
  (JNIEnv *, jclass, jlong, jlong, jintArray, jintArray);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    aeCreateFileEvent0
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_aeCreateFileEvent0
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    aeUpdateFileEvent0
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_aeUpdateFileEvent0
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    aeDeleteFileEvent0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_aeDeleteFileEvent0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    aeDeleteEventLoop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_aeDeleteEventLoop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    setBlocking
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_setBlocking
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    setSoLinger
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_setSoLinger
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    setReusePort
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_setReusePort
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    setRcvBuf
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_setRcvBuf
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    setTcpNoDelay
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_setTcpNoDelay
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    setBroadcast
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_setBroadcast
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    setIpTransparent
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_setIpTransparent
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    createIPv4TcpFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vproxy_vfd_posix_GeneralPosix_createIPv4TcpFD
  (JNIEnv *, jobject);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    createIPv6TcpFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vproxy_vfd_posix_GeneralPosix_createIPv6TcpFD
  (JNIEnv *, jobject);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    createIPv4UdpFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vproxy_vfd_posix_GeneralPosix_createIPv4UdpFD
  (JNIEnv *, jobject);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    createIPv6UdpFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vproxy_vfd_posix_GeneralPosix_createIPv6UdpFD
  (JNIEnv *, jobject);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    createUnixDomainSocketFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_vproxy_vfd_posix_GeneralPosix_createUnixDomainSocketFD
  (JNIEnv *, jobject);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    bindIPv4
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_bindIPv4
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    bindIPv6
 * Signature: (ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_bindIPv6
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    bindUnixDomainSocket
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_bindUnixDomainSocket
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    accept
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_vproxy_vfd_posix_GeneralPosix_accept
  (JNIEnv *, jobject, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    connectIPv4
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_connectIPv4
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    connectIPv6
 * Signature: (ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_connectIPv6
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    finishConnect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_finishConnect
  (JNIEnv *, jobject, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    shutdownOutput
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_vproxy_vfd_posix_GeneralPosix_shutdownOutput
  (JNIEnv *, jobject, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    getIPv4Local
 * Signature: (I)Lvproxy/vfd/posix/VSocketAddress;
 */
JNIEXPORT jobject JNICALL Java_vproxy_vfd_posix_GeneralPosix_getIPv4Local
  (JNIEnv *, jobject, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    getIPv6Local
 * Signature: (I)Lvproxy/vfd/posix/VSocketAddress;
 */
JNIEXPORT jobject JNICALL Java_vproxy_vfd_posix_GeneralPosix_getIPv6Local
  (JNIEnv *, jobject, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    getIPv4Remote
 * Signature: (I)Lvproxy/vfd/posix/VSocketAddress;
 */
JNIEXPORT jobject JNICALL Java_vproxy_vfd_posix_GeneralPosix_getIPv4Remote
  (JNIEnv *, jobject, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    getIPv6Remote
 * Signature: (I)Lvproxy/vfd/posix/VSocketAddress;
 */
JNIEXPORT jobject JNICALL Java_vproxy_vfd_posix_GeneralPosix_getIPv6Remote
  (JNIEnv *, jobject, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    getUDSLocal
 * Signature: (I)Lvproxy/vfd/posix/VSocketAddress;
 */
JNIEXPORT jobject JNICALL Java_vproxy_vfd_posix_GeneralPosix_getUDSLocal
  (JNIEnv *, jobject, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    getUDSRemote
 * Signature: (I)Lvproxy/vfd/posix/VSocketAddress;
 */
JNIEXPORT jobject JNICALL Java_vproxy_vfd_posix_GeneralPosix_getUDSRemote
  (JNIEnv *, jobject, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    read
 * Signature: (ILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_vproxy_vfd_posix_GeneralPosix_read
  (JNIEnv *, jobject, jint, jobject, jint, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    write
 * Signature: (ILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_vproxy_vfd_posix_GeneralPosix_write
  (JNIEnv *, jobject, jint, jobject, jint, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    sendtoIPv4
 * Signature: (ILjava/nio/ByteBuffer;IIII)I
 */
JNIEXPORT jint JNICALL Java_vproxy_vfd_posix_GeneralPosix_sendtoIPv4
  (JNIEnv *, jobject, jint, jobject, jint, jint, jint, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    sendtoIPv6
 * Signature: (ILjava/nio/ByteBuffer;IILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_vproxy_vfd_posix_GeneralPosix_sendtoIPv6
  (JNIEnv *, jobject, jint, jobject, jint, jint, jstring, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    recvfromIPv4
 * Signature: (ILjava/nio/ByteBuffer;II)Lvproxy/vfd/posix/UDPRecvResult;
 */
JNIEXPORT jobject JNICALL Java_vproxy_vfd_posix_GeneralPosix_recvfromIPv4
  (JNIEnv *, jobject, jint, jobject, jint, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    recvfromIPv6
 * Signature: (ILjava/nio/ByteBuffer;II)Lvproxy/vfd/posix/UDPRecvResult;
 */
JNIEXPORT jobject JNICALL Java_vproxy_vfd_posix_GeneralPosix_recvfromIPv6
  (JNIEnv *, jobject, jint, jobject, jint, jint);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    currentTimeMillis
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_vproxy_vfd_posix_GeneralPosix_currentTimeMillis
  (JNIEnv *, jobject);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    tapNonBlockingSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_vproxy_vfd_posix_GeneralPosix_tapNonBlockingSupported
  (JNIEnv *, jobject);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    tunNonBlockingSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_vproxy_vfd_posix_GeneralPosix_tunNonBlockingSupported
  (JNIEnv *, jobject);

/*
 * Class:     vproxy_vfd_posix_GeneralPosix
 * Method:    createTapFD
 * Signature: (Ljava/lang/String;Z)Lvproxy/vfd/TapInfo;
 */
JNIEXPORT jobject JNICALL Java_vproxy_vfd_posix_GeneralPosix_createTapFD
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
