/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vproxy_fstack_FStack */

#ifndef _Included_vproxy_fstack_FStack
#define _Included_vproxy_fstack_FStack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vproxy_fstack_FStack
 * Method:    ff_init0
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vproxy_fstack_FStack_ff_1init0
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     vproxy_fstack_FStack
 * Method:    ff_run0
 * Signature: (Ljava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_vproxy_fstack_FStack_ff_1run0
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
