package io.vproxy.vproxyx.aimix;

import io.vproxy.base.util.Logger;
import io.vproxy.base.util.exception.XException;
import vjson.JSON;
import vjson.JSONObject;
import vjson.deserializer.rule.*;
import vjson.util.ArrayBuilder;
import vjson.util.ObjectBuilder;

import java.util.ArrayList;
import java.util.List;

public class OllamaApi {
    private OllamaApi() {
    }

    public static class OllamaObject {
        public OllamaError error;

        public static final ObjectRule<OllamaObject> rule = new ObjectRule<>(OllamaObject::new)
            .put("error", (o, v) -> o.error = v, OllamaError.rule);
    }

    public static class OllamaError {
        public String message;

        public static final Rule<OllamaError> rule = new ObjectRule<>(OllamaError::new)
            .put("message", (o, v) -> o.message = v, StringRule.get());
    }

    public static class OllamaChatRequest implements JSONObject {
        public String model;
        public List<OllamaMessage> messages = new ArrayList<>();
        public boolean stream;
        public OllamaOptions options;

        public static final Rule<OllamaChatRequest> rule = new ObjectRule<>(OllamaChatRequest::new)
            .put("model", (o, v) -> o.model = v, StringRule.get())
            .put("messages", (o, v) -> o.messages = v,
                new ArrayRule<List<OllamaMessage>, OllamaMessage>(ArrayList::new, List::add, OllamaMessage.rule))
            .put("stream", (o, v) -> o.stream = v, BoolRule.get())
            .put("options", (o, v) -> o.options = v, OllamaOptions.rule);

        @Override
        public JSON.Object toJson() {
            return new ObjectBuilder()
                .put("model", model)
                .putArray("messages", arr -> messages.forEach(e -> arr.addInst(e.toJson())))
                .put("stream", stream)
                .putInst("options", options != null ? options.toJson() : null)
                .build();
        }
    }

    public static class OllamaMessage implements JSONObject {
        public Role role;
        public String content;
        public List<String> images;

        public static final Rule<OllamaMessage> rule = new ObjectRule<>(OllamaMessage::new)
            .put("role", (o, v) -> o.role = Role.valueOf(v), StringRule.get())
            .put("content", (o, v) -> o.content = v, StringRule.get())
            .put("images", (o, v) -> o.images = v, new ArrayRule<List<String>, String>(
                ArrayList::new, List::add, StringRule.get()));

        @Override
        public JSON.Object toJson() {
            return new ObjectBuilder()
                .put("role", role.toString())
                .put("content", content)
                .putNullableInst("images", images == null,
                    () -> new ArrayBuilder().iterable(images, ArrayBuilder::add).build())
                .build();
        }
    }

    public static class OllamaOptions implements JSONObject {
        public int numThread;
        // FIXME: may need them later ? generated by DeepSeek V3 685b Q8
        // public double temperature;
        // public int topK;
        // public double topP;
        // public int numPredict;

        public static final Rule<OllamaOptions> rule = new ObjectRule<>(OllamaOptions::new)
            .put("num_thread", (o, v) -> o.numThread = v, IntRule.get())
            // .put("temperature", (o, v) -> o.temperature = v, DoubleRule.get())
            // .put("top_k", (o, v) -> o.topK = v, IntRule.get())
            // .put("top_p", (o, v) -> o.topP = v, DoubleRule.get())
            // .put("num_predict", (o, v) -> o.numPredict = v, IntRule.get())
            ;

        @Override
        public JSON.Object toJson() {
            var ob = new ObjectBuilder();
            if (numThread != 0) {
                ob.put("num_thread", numThread);
            }
            // .put("temperature", temperature)
            // .put("top_k", topK)
            // .put("top_p", topP)
            // .put("num_predict", numPredict)
            return ob.build();
        }

        public void validate(String path) throws XException {
            if (numThread != 0) {
                if (numThread < 0) {
                    throw new XException(path + ".num_thread should be a positive integer");
                }
            }
        }
    }

    public static class OllamaChatResponse extends OllamaObject implements JSONObject {
        public String model;
        public OllamaMessage message;
        public String createdAt;
        public boolean done;
        public String doneReason;
        public long totalDuration;
        public long loadDuration;
        public int promptEvalCount;
        public long promptEvalDuration;
        public int evalCount;
        public long evalDuration;

        public static final Rule<OllamaChatResponse> rule = new ObjectRule<>(OllamaChatResponse::new, OllamaObject.rule)
            .put("model", (o, v) -> o.model = v, StringRule.get())
            .put("message", (o, v) -> o.message = v, OllamaMessage.rule)
            .put("created_at", (o, v) -> o.createdAt = v, StringRule.get())
            .put("done", (o, v) -> o.done = v, BoolRule.get())
            .put("done_reason", (o, v) -> o.doneReason = v, StringRule.get())
            .put("total_duration", (o, v) -> o.totalDuration = v, LongRule.get())
            .put("load_duration", (o, v) -> o.loadDuration = v, LongRule.get())
            .put("prompt_eval_count", (o, v) -> o.promptEvalCount = v, IntRule.get())
            .put("prompt_eval_duration", (o, v) -> o.promptEvalDuration = v, LongRule.get())
            .put("eval_count", (o, v) -> o.evalCount = v, IntRule.get())
            .put("eval_duration", (o, v) -> o.evalDuration = v, LongRule.get());

        @Override
        public JSON.Object toJson() {
            return new ObjectBuilder()
                .put("model", model)
                .putInst("message", message.toJson())
                .put("created_at", createdAt)
                .put("done", done)
                .put("done_reason", doneReason)
                .put("total_duration", totalDuration)
                .put("load_duration", loadDuration)
                .put("prompt_eval_count", promptEvalCount)
                .put("prompt_eval_duration", promptEvalDuration)
                .put("eval_count", evalCount)
                .put("eval_duration", evalDuration)
                .build();
        }

        public OpenAiApi.CompletionResponse toOpenAICompletionResponse(boolean delta) {
            var openaiResp = new OpenAiApi.CompletionResponse();
            openaiResp.choices = List.of(toOpenAiChoice(delta));
            openaiResp.created = System.currentTimeMillis() / 1000;
            openaiResp.model = model;
            if (done && totalDuration > 0) {
                openaiResp.usage = new OpenAiApi.CompletionUsage();
                openaiResp.usage.totalTokens = promptEvalCount + evalCount;
                openaiResp.usage.promptTokens = promptEvalCount;
                openaiResp.usage.completionTokens = evalCount;
            }
            return openaiResp;
        }

        private OpenAiApi.CompletionChoice toOpenAiChoice(boolean delta) {
            var openaiChoice = new OpenAiApi.CompletionChoice();
            openaiChoice.finishReason = doneReason;
            openaiChoice.index = 0;
            var msg = new OpenAiApi.CompletionChoiceMessage();
            if (delta) {
                openaiChoice.delta = msg;
            } else {
                openaiChoice.message = msg;
            }
            msg.role = Role.assistant;
            msg.content = message.content;
            return openaiChoice;
        }

        public void printToStdout(Config config) {
            Logger.alert(config.printResponseSymbol + " CompletionResponse");
            System.out.print(message.content);
            System.out.println();
            Logger.alert(config.printResponseSymbol + " END");
        }
    }
}
